Board/Board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    # pybo/ 로 시작되는 URL이 요청되면 이제 pybo/urls.py 파일의 매핑정보를 읽어서 처리하라는 의미이다.
    # 따라서 이제 pybo/question/create, pybo/answer/create등의 URL이 추가되더라도
    # config/urls.py 파일을 수정할 필요없이 pybo/urls.py 파일만 수정하면 될것이다.

    # 뒤에 슬래시를 붙여주면 웹브라우저 주소창에 http://localhost:8000/pybo 라고 입력해도 자동으로 http://localhost:8000/pybo/ 처럼 변환된다. 이렇게 되는 이유는
    # URL을 정규화하는 장고의 기능 때문이다.
]

Board/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

Board/pybo/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # ForeignKey는 다른 모델과의 연결을 의미한다.
    # on_delete=models.CASCADE의 의미는 이 답변과 연결된 질문(Question)이 삭제될 경우 답변(Answer)도 함께 삭제된다는 의미이다.
    content = models.TextField()
    create_date = models.DateTimeField()

Board/pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

Board/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from pybo.models import Question
from .forms import QuestionForm, AnswerForm


# Create your views here.


def index(request):
    question_list = Question.objects.order_by('-create_date')  # 조회결과 역순정렬
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


def question_create(request):
    if request.method == 'POST':  # 생성에 적합함
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

Board/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

Board/templates/pybo/question_detail.html
{#{% load static %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">#}

{% extends 'base.html' %}
{% block content %}

    <div class="container my-3">
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2">
                        {{ question.create_date }}
                    </div>
                </div>
            </div>
        </div>
        <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
        {% for answer in question.answer_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            {{ answer.create_date }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <input type="submit" value="답변등록" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

Board/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            {#            {{ form.as_p }} <!-- form은 question_create 함수에서 전달된 QuestionForm의 객체 -->#}
            {#            <!-- 제목과 내용같은 폼 입력항목을 위한 HTML코드들을 자동으로 만들어 낸다. -->#}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea class="form-control" name="content"
                          id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                <!-- 오류가 발생했을 경우 기존에 입력했던 값을 유지하기 위함 -->
                <!-- |default_if_none:''의 의미는 폼 데이터(form.subject.value)에 값이 없을 경우
                None 이라는 문자열이 표시되는데 None 대신 공백으로 표시하기 위한 필터 -->
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

Board/templates/pybo/question_list.html
{#{% load static %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">#}

{% extends 'base.html' %}
{% block content %}

    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                        </td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
    </div>

{% endblock %}